### ISSUE TITLE
problem with validates uniqueness

### ISSUE THREAD

**Issue by rlisowski** [nay/never_wastes#5]
When I use 

```
validates :email, presence: true, uniqueness: true
```

with never_wastes it search in whole table instead of only in undeleted records.
Query which check uniqueness looks like that:

```
 SELECT 1 FROM `users` WHERE (`users`.`email` = BINARY 'xxxx@gmail.com' AND `users`.`id` != 12) LIMIT 1
```

Can you have any idea how can I fix that? How to force uniqueness validation to work only in undeleted records?

Regards
Rafał

**Comment by rlisowski** [comment]
Uniqueness validation don't use default scope.
Doh, after a while I figure it out. Just add a scope:

```
validates :email, presence: true, uniqueness: { scope: :deleted_at}
```

**Comment by nay** [comment]
My idea is the same way. Glad that it is fixed. Thank you very much for a report.
